### **Data Dataset**

In [69]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [70]:
df = pd.read_csv(r"D:\261100670031\AML_LAB\LAB\Data\Data.csv" )
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [71]:
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [72]:
df.tail()

   Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     str
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     str
dtypes: float64(2), str(2)
memory usage: 452.0 bytes

In [74]:
df.dtypes

Country          str
Age          float64
Salary       float64
Purchased        str
dtype: object

In [75]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [76]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [77]:
df.duplicated().sum()

np.int64(0)

In [78]:
# Split independent variables
# loc uses labels
# iloc uses integer positions(numbers from 0 to the length of the data)

df
X = df.iloc[:, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [79]:
# Split dependent variable
y = df.iloc[:,3].values
y

<StringArray>
['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
Length: 10, dtype: str

In [80]:
# Taking care of missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:,1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [81]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X =  LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [82]:
# Encoding the Independent Variable
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = "passthrough")
X = ct.fit_transform(X)

X.astype(int)

array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 63777],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [83]:
# Encoding the Dependent Variable
from sklearn.preprocessing import LabelEncoder

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [84]:
# Split data into Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 45)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [85]:
# X_train.astype(int)
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object)

In [86]:
X_train.astype(int)
# X_test

array([[    0,     0,     1,    27, 48000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    35, 58000],
       [    1,     0,     0,    48, 79000],
       [    1,     0,     0,    44, 72000],
       [    0,     0,     1,    38, 61000]])

In [87]:
# Feature Scaling
# sc_X = (X[1]-mean) / standard deviation
# For classification SC for regression no SC
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

In [88]:
X_test

array([[ 0.,  0.,  0., -1., -1.],
       [ 0.,  0.,  0.,  1.,  1.]])

In [89]:
X_train

array([[-1.        , -0.37796447,  1.29099445, -1.82709535, -1.45240802],
       [-1.        ,  2.64575131, -0.77459667,  1.47603773,  1.53784378],
       [ 1.        , -0.37796447, -0.77459667, -0.39095053,  0.17087153],
       [-1.        , -0.37796447,  1.29099445, -0.1356359 , -1.11066496],
       [ 1.        , -0.37796447, -0.77459667, -0.6781795 , -0.59805036],
       [ 1.        , -0.37796447, -0.77459667,  1.18880877,  1.19610072],
       [ 1.        , -0.37796447, -0.77459667,  0.61435084,  0.59805036],
       [-1.        , -0.37796447,  1.29099445, -0.24733605, -0.34174306]])

### **bestsellers with categories**

In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [91]:
df = pd.read_csv("D:\\261100670031\\AML_LAB\\LAB\\Data\\bestsellers with categories.csv")
print("Dataset loaded successfully!")
df

Dataset loaded successfully!

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [92]:
print("Shape:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()

Shape: (550, 7)

Data Types:
Name               str
Author             str
User Rating    float64
Reviews          int64
Price            int64
Year             int64
Genre              str
dtype: object

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    str
 1   Author       550 non-null    str
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    str
dtypes: float64(1), int64(3), str(3)
memory usage: 30.2 KB

In [93]:
df.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [94]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [95]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

In [96]:
print("Unique values in each column:")
print(df.nunique())

Unique values in each column:
Name           351
Author         248
User Rating     14
Reviews        346
Price           40
Year            11
Genre            2
dtype: int64

In [97]:
df.columns = df.columns.str.strip().str.replace(" ", "_")

print(df.columns)

Index(['Name', 'Author', 'User_Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='str')

In [98]:
df["Name"] = df["Name"].str.strip()
df["Author"] = df["Author"].str.strip()
df["Genre"] = df["Genre"].str.strip()

In [99]:
print("User Rating range:", df["User_Rating"].min(), "-", df["User_Rating"].max())
print("Reviews range:", df["Reviews"].min(), "-", df["Reviews"].max())
print("Price range:", df["Price"].min(), "-", df["Price"].max())
print("Year range:", df["Year"].min(), "-", df["Year"].max())

User Rating range: 3.3 - 4.9
Reviews range: 37 - 87841
Price range: 0 - 105
Year range: 2009 - 2019

In [100]:
# plt.figure(figsize=(6, 4))
# plt.boxplot(df["Reviews"])
# plt.title("Boxplot of Reviews")
# plt.ylabel("Reviews")
# plt.show()

In [101]:
# plt.figure(figsize=(6, 4))
# plt.boxplot(df["Price"])
# plt.title("Boxplot of Price")
# plt.ylabel("Price")
# plt.show()

In [102]:
# plt.figure(figsize=(6, 4))
# plt.boxplot(df["User_Rating"])
# plt.title("Boxplot of User Rating")
# plt.ylabel("User Rating")
# plt.show()

In [107]:
X = df.drop("Genre", axis=1)
y = df["Genre"]

In [108]:
X = df[["User_Rating", "Reviews", "Price", "Year"]]
y = df["Genre"]

In [109]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(y)

print("Genre Mapping:")
print(dict(zip(le.classes_, le.transform(le.classes_))))

Genre Mapping:
{np.int64(0): np.int64(0), np.int64(1): np.int64(1)}

In [110]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (440, 4)
X_test: (110, 4)
y_train: (440,)
y_test: (110,)

In [111]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [112]:
print("X_train after scaling:")
print(X_train_scaled[:5])

print("\nX_test after scaling:")
print(X_test_scaled[:5])

X_train after scaling:
[[ 1.25023492  0.68656862 -0.77971545  1.59987215]
 [ 0.35503009 -0.71523673 -0.3967126   0.33207612]
 [-0.54017473 -0.82496383 -0.87546616  0.64902513]
 [-0.09257232 -0.20993072  1.03954806 -0.3018219 ]
 [-0.54017473 -0.98652843 -0.49246331 -1.25266892]]

X_test after scaling:
[[-0.09257232 -0.29167785  0.36929308  0.96597413]
 [ 0.35503009  0.36194832 -0.01370976 -0.3018219 ]
 [ 1.25023492  0.68656862 -0.77971545  0.96597413]
 [-1.88298196  0.17178977 -0.68396474  1.28292314]
 [ 0.8026325  -0.49209865 -0.87546616  1.59987215]]

### **bestsellers**